---
title: "Influencia de la Actividad Física en el Rendimiento Académico y Bienestar de Estudiantes Universitarios"
author: "Grupo 2 - PG1"
lang: es
format:
  html:
    theme: flatly
    toc: true
    toc-location: right
    toc-depth: 4
    smooth-scroll: true
    title-block-banner: true
    embed-resources: true
    code-fold: true
    code-summary: "Mostrar código"
    number-sections: true
execute:
  warning: false
  message: false
editor: visual
---

# Introducción

## Relevancia

Estudiar la relación entre actividad física, sueño, estrés y rendimiento académico en universitarios es importante porque la vida académica genera altas cargas de trabajo, estrés y hábitos poco saludables, como el sedentarismo y la falta de sueño, que afectan el bienestar y desempeño estudiantil. Diversas investigaciones señalan que la actividad física mejora la calidad del sueño y reduce el estrés académico, favoreciendo un mejor rendimiento; además, una mala calidad de sueño se relaciona significativamente con bajas calificaciones, convirtiéndose en un factor clave en el desempeño universitario.

## Objetivos

### General

Determinar cómo influye la actividad física que realizan los estudiantes de UTEC en su desempeño académico y bienestar integral durante el segundo semestre del 2025.

### Específicos

1.  Explorar la relación entre la frecuencia semanal de actividad física y el promedio ponderado en estudiantes de UTEC durante el segundo semestre del 2025.

2.  Comparar el nivel de concentración autopercibido entre estudiantes que practican diferentes tipos de actividad física en UTEC durante el segundo semestre del 2025.

3.  Evaluar la influencia de las horas de sueño sobre el nivel de estrés reportado en estudiantes de UTEC que realizan actividad física regular durante el segundo semestre del 2025.

# Datos

## Población

Estudiantes de la Universidad de Ingeniería y Tecnología (UTEC) en el periodo 2025-2.

## Muestra CAMBIAR

1,045 estudiantes de la Universidad de Ingeniería y Tecnología (UTEC) en el periodo 2025-2.

## Unidad muestral

Cada estudiante de la Universidad de Ingeniería y Tecnología (UTEC) en el periodo 2025-2.

## Tipo de muestreo

Muestreo no probabilístico por conveniencia.

## 2.5. Variables

## 2.6. Limpieza

### 2.6.1. Carga de Datos

### 2.6.2. Renombramiento/Selección

### 2.6.3. Valores faltantes

### 2.6.4. Cambios Simples

### 2.6.5. Cambios complejos

### 2.6.6. Valores extraños

### 2.6.7. Manejo de Datos repetidos

### 2.6.8. Muestra efectiva

### 2.6.9. Formato

### 2.6.10. Tabla de valores faltantes final

# Análisis descriptivo

## 3.1. Análisis univariado

### 3.1.1. Variables Categóricas

### 3.1.2. Variables Numéricas

## 3.2. Análisis Multivariado

### 3.2.1. Análisis Multivariado 1: Sexo vs Frecuencia AF

### 3.2.2. Análisis Multivariado 2: Ranking vs Nivel de Estrés

## 3.3. Análisis de Interacción (por Objetivos Específicos)

### 3.3.1. Objetivo Específico 1

### 3.3.2. Objetivo Específico 2

### 3.3.3. Objetivo Específico 3

# Análisis Probabilístico

## Probabilidad Empírica

## Propiedades de Probabilidad Aplicadas

## 4.3. Probabilidad Condicional

## 4.4. Teorema de Bayes con Probabilidad Total

## 4.5. Variables aleatorias discretas

## 4.6. Variables aleatorias continuas

# Conclusiones

5.1. Resumen de Hallazgos por Objetivos Específicos

5.2. Conclusiones probabilísticas

5.3. Limitaciones del Estudio

5.4. Posible Investigación Futura
